title: Just Vibe Studios
description: Just Vibe Studios documentation
theme: just-the-docs

url: https://strainx.github.io

aux_links:
  Template Repository: https://github.com/strainx/just-the-docs-justvibestudios
